apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%　 #アップデート中に最大に増やしていいいポッドの数
      maxUnavailable: 25%　#アップデート中に最大で２５％のインスタンスが使用できなくなる
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: test-sa
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80　 # コンテナが開けるポート
        - name: regi-test
        - image: myprivateregistry.com:5000/nginx:alpine #レジストリを指定
      imagePullSecret:
      - name: secret-name



# image pull secret で検索すれば引っかかる
root@controlplane ~ ➜  k create secret docker-registry private-reg-cred --docker-username=dock_user --docker-password=dock_password --docker-server=myprivateregistry.com:5000 --docker-email=dock_user@myprivateregistry.com
secret/private-reg-cred created


